(deftheme pop_os
  "Created 2023-12-12.")

(custom-theme-set-faces
 'pop_os
 '(cursor ((t (:background "#FFFFFF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "#34E2E2")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "#34E2E2")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#F15D22"))))
 '(highlight ((t (:weight bold :foreground "#FFFFFF"))))
 '(region ((t (:extend t :background "#49B9C7" :foreground "#FFFFFF"))))
 '(shadow ((t (:foreground "#88807C"))))
 '(secondary-selection ((t (:extend t :background "#4f5b66"))))
 '(trailing-whitespace ((t (:background "#bf616a"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#F15D22"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#88807C"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#88807C"))))
 '(font-lock-constant-face ((t (:foreground "#b48ead"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#88807C"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#8fa1b3"))))
 '(font-lock-keyword-face ((t (:foreground "#F15D22"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#c0c5ce"))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:weight bold :foreground "#c0c5ce"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#c0c5ce"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#c0c5ce"))))
 '(font-lock-string-face ((t (:foreground "#4E9A06"))))
 '(font-lock-type-face ((t (:foreground "#C4A000"))))
 '(font-lock-variable-name-face ((t (:foreground "#bf616a"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#C4A000"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#F15D22"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#4f5b66" :background "#2b303b"))))
 '(header-line ((t (:foreground "#c0c5ce" :background "#2b303b"))))
 '(tooltip ((t (:foreground "#c0c5ce" :background "#232830"))))
 '(mode-line ((t (:foreground "#c0c5ce" :background "#232830"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#F15D22"))))
 '(mode-line-highlight ((t (:weight bold :underline (:color "#AD7FA8" :style line :position nil) :foreground "#b48ead"))))
 '(mode-line-inactive ((t (:foreground "#88807C" :background "#232830"))))
 '(isearch ((t (:weight bold :foreground "#dfdfdf" :background "#3465A4"))))
 '(isearch-fail ((t (:weight bold :foreground "#CC0000" :background "#333333"))))
 '(lazy-highlight ((t (:weight bold :foreground "#dfdfdf" :background "#3465A4"))))
 '(match ((t (:weight bold :foreground "#4E9A06" :background "#333333"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#333333" :foreground "#f2f2f2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 98 :width normal :foundry "PfEd" :family "Fira Mono")))))

;;;; ivy - dark

(provide-theme 'pop_os)
